### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prince-chrismc**
Will the bot comment?!

### CODE REVIEW

**Comment by prince-chrismc** [comment]
success!

**Comment by prince-chrismc** [comment]
Test two

**Comment by prince-chrismc** [comment]
fix bad code?

**Comment by prince-chrismc** [comment]
Can not request @RubenRBS :/

**Comment by prince-chrismc** [comment]
testing from the bot

**Comment by prince-chrismc** [comment]
quick refactor

**Comment by prince-chrismc** [comment]
closer....

**Comment by prince-chrismc** [comment]
Success!

**Comment by ericLemanissier** [comment]
great ! 
Please note that there is a bug caused by [pr_changed_files](https://github.com/conan-io/conan-center-index/blob/master/.github/actions/pr_changed_files/action.yml) action: it handles `**` as if it was a single `*`, so patterns like [`recipes/qt/**`](https://github.com/prince-chrismc/conan-center-index/blob/master/.github/workflows/alter-community.yml#LL33C18-L33C31) match `recipes/qt/config.yml`, but not `recipes/qt/6.x.x/conanfile.py`
I'll make a pull request which makes `pr_changed_files` properly handle `**` when they are at the end of a pattern. It's easy in this case, because we just have to stop the matching earlier. I'll make the action fail if `**` is found not at the end of the pattern.

**Comment by ericLemanissier** [comment]
the hard part of this thing is to decide when to actually create the comment. As it is now, it'll trigger when the PR is opened, pushed or reopened. We probably don't want to post a new message for each commit. On the other hand, posting a message only when the PR is opened or reopened may not be enough. The devil is in the details...

**Comment by prince-chrismc** [comment]
I initially planned to have it limited to just create so it only happens once but for testing it just wanted one

I can fix the code to do `*/*` instead that seems more easy but a failure would be good too!

**Comment by prince-chrismc** [comment]
Moved to CCI for large feedback sample but this is a side thing for now

**Pull request closed without merging**
